-- Luacheck – e_core FiveM resource (Fázis 4).
-- Cél: tiszta `luacheck .` (0 warning) + FiveM / oxmysql környezet.

std = "lua54"

exclude_files = {
    "html/**",
    --- Windows + POSIX: mindkét minta (luacheck path normalizálása eltérhet).
    "fxmanifest.lua",
    "**/fxmanifest.lua",
    "types/**",
    "**/types/**",
}

max_line_length = false
allow_defined_top = true
unused_args = false
unused = false

read_globals = {
    "lib",
    "MySQL",
    "json",
    "exports",
    "Citizen",
    "CreateThread",
    "Wait",
    "SetTimeout",
    "ClearTimeout",
    "RegisterNetEvent",
    "AddEventHandler",
    "RegisterServerEvent",
    "RegisterCommand",
    "TriggerClientEvent",
    "TriggerServerEvent",
    "TriggerEvent",
    "TriggerLatentClientEvent",
    "GetCurrentResourceName",
    "GetResourceState",
    "GetInvokingResource",
    "GetConvar",
    "GetConvarInt",
    "SetConvarReplicated",
    "GetResourceMetadata",
    "source",
    "vector3",
    "vector4",
    "vec",
    "promise",
    "PlayerPedId",
    "PlayerId",
    "GetPlayerServerId",
    "GetActivePlayers",
    "LocalPlayer",
    "SendNUIMessage",
    "RegisterNUICallback",
    "SetNuiFocus",
    "IsNuiFocused",
    "GetEntityCoords",
    "DoesEntityExist",
    "DeleteEntity",
    "SetEntityCoords",
    "GetPlayerName",
    "PerformHttpRequest",
    "LoadResourceFile",
    "CreateVehicle",
    "Entity",
    "NetworkGetEntityFromNetworkId",
    "GetVehicleNumberPlateText",
    "GetGameTimer",
    "GetHashKey",
    "joaat",
    "IsPauseMenuActive",
    "RegisterKeyMapping",
    "ExecuteCommand",
    "GetVehiclePedIsIn",
    "SetBoatAnchor",
    "SetVehicleNumberPlateText",
    "SetVehicleProperties",
    "CreateVehicleServerSetter",
    "NetworkGetEntityOwner",
    "NetworkGetNetworkIdFromEntity",
    "NetworkDoesEntityExistWithNetworkId",
    "NetToVeh",
    "SetBoatFrozenWhenAnchored",
    "IsPedCuffed",
    "IsPedFatallyInjured",
    "IsEntityDead",
    "IsPedInAnyVehicle",
    "IsPedSwimming",
    "IsPedOnFoot",
    "AddBlipForCoord",
    "SetBlipSprite",
    "SetBlipScale",
    "SetBlipColour",
    "SetBlipAsShortRange",
    "BeginTextCommandSetBlipName",
    "AddTextComponentString",
    "EndTextCommandSetBlipName",
    "DoesAnimDictExist",
    "HasAnimDictLoaded",
    "RequestAnimDict",
    "IsModelValid",
    "HasModelLoaded",
    "RequestModel",
    "RequestNamedPtfxAsset",
    "HasNamedPtfxAssetLoaded",

    --- Cfx resource manifest (fxmanifest.lua) – függvényszerű hívások.
    "fx_version",
    "game",
    "description",
    "version",
    "shared_scripts",
    "client_scripts",
    "server_scripts",
    "ui_page",
    "files",
    "lua54",
    "dependencies",
}

globals = {
    --- Bridge kliens: `_PlayerPedId = PlayerPedId()` (nem read-only).
    "_PlayerPedId",

    "ESX",
    "QBCore",
    "eCore",
    "hf",
    "eCoreErr",
    "eCoreConfig",
    "ECO",
    "CORE_READY",
    "REGISTERED_ITEMS",
    "Config",
    "FRAMEWORK",
    "ESX_CORE",
    "QB_CORE",
    "sharedEvents",
    "ESXEvents",
    "QBEvents",
    "locales",
    "OX_INVENTORY",
    "QS_INVENTORY",
    "CUSTOM_INVENTORY",
    "AVP_GRID_INVENTORY",
    "OX_LIB",
    "HUD17",
    "INSIDE_SCRIPTS_UI",
    "ECORE_DB_MIGRATIONS",
    "ECORE_DB_SCHEMA_TARGET",
    "e_core_run_db_migrations",
    "e_core_get_applied_migration_id",
    "loadMeta",
    "saveMeta",
    "saveAllMeta",
    "prepareMeta",
    "addOfflineLabor",
    "syncRequest",
    "saveRequest",
    "messageIfLevelChange",
    "checkMetaExists",
    "setMeta",
    "getMeta",
    "registerMeta",
    "getAbility",
    "setAbility",
    "addAbility",
    "removeAbility",
    "getLabor",
    "setLabor",
    "addLabor",
    "removeLabor",
    "laborIncrease",
    "getLevel",
    "getDiscounts",
    "checkLevelChange",
    "configCheck",
    "cLog",
    "print_r",
    "createBlip",
    "animDictLoader",
    "modelLoader",
    "fxLoader",
    "createDiscordLog",
    "translate",
    "translateU",
    "e_core_apply_esx_config",
    "e_core_apply_qb_config",
    "nuiInit",
}
