---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ekhion.
--- DateTime: 2023. 01. 12. 22:59
---

function prepareMeta(playerId, meta)

    if type(meta) ~= 'table' then
        meta = {}
    end

    ECO.meta[playerId] = meta

    if Config.systemMode.labor then

        ECO.meta[playerId]['labor'] = meta['labor'] or { val = Config.defaultLabor, time = os.time() }

        if Config.systemMode.profession then

            ECO.meta[playerId]['crafting'] = meta['crafting'] or {}
            ECO.meta[playerId]['harvesting'] = meta['harvesting'] or {}
            ECO.meta[playerId]['reputation'] = meta['reputation'] or {}

            --ECO.meta[playerId]['special'] = meta['special'] or {}
            --ECO.meta[playerId]['guidebook'] = meta['guidebook'] or {}
            --ECO.meta[playerId]['achievement'] = meta['achievement'] or {}
        end
    end

    ECO.meta[playerId]['login'] = os.time()
    ECO.meta[playerId]['logout'] = meta['logout'] or 0
end


-- proficiency examples:
--[[
    ECO.meta[playerId]['harvesting']['husbandry'] = ECO.meta[playerId]['harvesting']['husbandry'] or 0
    ECO.meta[playerId]['harvesting']['farming'] = ECO.meta[playerId]['harvesting']['farming'] or 0
    ECO.meta[playerId]['harvesting']['fishing'] = ECO.meta[playerId]['harvesting']['fishing'] or 0
    ECO.meta[playerId]['harvesting']['logging'] = ECO.meta[playerId]['harvesting']['logging'] or 0
    ECO.meta[playerId]['harvesting']['gathering'] = ECO.meta[playerId]['harvesting']['gathering'] or 0
    ECO.meta[playerId]['harvesting']['mining'] = ECO.meta[playerId]['harvesting']['mining'] or 0

    ECO.meta[playerId]['special']['driving_distance'] = ECO.meta[playerId]['special']['driving_distance'] or 0

    ECO.meta[playerId]['reputation']['burglar'] = ECO.meta[playerId]['reputation']['burglar'] or 0
    ECO.meta[playerId]['reputation']['thief'] = ECO.meta[playerId]['reputation']['thief'] or 0
    ECO.meta[playerId]['reputation']['car_thief'] = ECO.meta[playerId]['reputation']['car_thief'] or 0
    ECO.meta[playerId]['reputation']['robber'] = ECO.meta[playerId]['reputation']['robber'] or 0
    ECO.meta[playerId]['reputation']['safe_cracker'] = ECO.meta[playerId]['reputation']['safe_cracker'] or 0
    ECO.meta[playerId]['reputation']['hitman'] = ECO.meta[playerId]['reputation']['hitman'] or 0
    ECO.meta[playerId]['reputation']['killer'] = ECO.meta[playerId]['reputation']['killer'] or 0
    ECO.meta[playerId]['reputation']['weapon_nepper'] = ECO.meta[playerId]['reputation']['weapon_nepper'] or 0
    ECO.meta[playerId]['reputation']['drug_nepper'] = ECO.meta[playerId]['reputation']['drug_nepper'] or 0
    ECO.meta[playerId]['reputation']['money_launderer'] = ECO.meta[playerId]['reputation']['money_launderer'] or 0
    ECO.meta[playerId]['reputation']['trader'] = ECO.meta[playerId]['reputation']['trader'] or 0
    ECO.meta[playerId]['reputation']['life_saver'] = ECO.meta[playerId]['reputation']['life_saver'] or 0
    ECO.meta[playerId]['reputation']['punityve'] = ECO.meta[playerId]['reputation']['punityve'] or 0
]]