---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ekhion.
--- DateTime: 2023. 03. 27. 14:33
---

function globalFunctions()

    local self = sharedGlobalFunctions()


    return self
end