--- Overrides bridge functions
--- Do not overwrite the bridge files.
--- Copy the function you want to modify here

-- function eCore:getInventory(playerData) end
-- function eCore:getPlayerMaxWeight(playerData) end
-- function eCore:getRegisteredItems() end
-- function eCore:getInventoryWeight(playerData) end
-- function eCore:canSwapItems(swappingItems, itemData, playerData) end
-- function eCore:canCarryItem(itemData, playerData) end
-- function eCore:getItemWeight(itemName, metadata) end